// A list of 50 famous quiz topics.
export const quizTopics = [
    'World Capitals',
    'The Solar System',
    'World War II History',
    'Famous Landmarks',
    'Human Anatomy',
    'Classic Literature',
    'The Olympic Games',
    'Greek Mythology',
    'Famous Inventions',
    'Marvel Cinematic Universe (MCU)',
    'Physics Basics',
    'World Cuisines',
    'Renaissance Art',
    'Dinosaurs',
    'The Roman Empire',
    'Pop Music: 1990s',
    'Chemistry Elements',
    'Flags of the World',
    'Shakespeare\'s Plays',
    'Automobile History',
    'Famous Scientists',
    'National Parks of the World',
    'Oscar-Winning Movies',
    'The Animal Kingdom',
    'Ancient Egypt',
    'Video Game History',
    'World Religions',
    'Famous Philosophers',
    'The Beatles',
    'Computer Science Pioneers',
    'Marine Biology',
    'Formula 1 Racing',
    'Famous Architects',
    'Brand Logos and Slogans',
    'The Cold War',
    'Disney & Pixar Films',
    'US Presidents',
    'Types of Musical Instruments',
    'Explorers and Discoveries',
    'Harry Potter Universe',
    'Medical Breakthroughs',
    'NBA Basketball Trivia',
    'Famous Kings and Queens',
    'International Space Station',
    'Cricket World Cup History',
    'Modern Art Movements',
    'Famous Speeches',
    'Coffee and Tea Trivia',
    'The Human Brain',
    'Legendary Athletes'
  ];